Repository Yadon079/learning-algorithm, pull requests merged in 2021-07, with the labels that each got.

#6 Weekly Pull Request - 박종찬
  JongChan-Park/quiz1.js
  JongChan-Park/quiz2.java
  JongChan-Park/quiz3.java
  JongChan-Park/quiz4.java
  JongChan-Park/quiz5.java
  JongChan-Park/quiz6.java
  JongChan-Park/quiz7.java
Labels: C

#7 Weekly Pull Request - 최현진
  Hyunjin-Choi/boj/boj_11650.cpp
  Hyunjin-Choi/boj/boj_21866.cpp
  Hyunjin-Choi/boj/boj_2309.cpp
  Hyunjin-Choi/boj/boj_6603.cpp
Labels: C

#8 Weekly Pull Request - 한선우
  Sunwoo-Han/boj/boj_14501.java
  Sunwoo-Han/boj/boj_16236.java
  Sunwoo-Han/programmers/bpMockexam.java
  Sunwoo-Han/programmers/sortBiggestNum.java
  Sunwoo-Han/programmers/sortHindex.java
Labels: Java

#9 Weekly Pull Request - 김민정
  Hyunjin-Choi/boj/boj_11047.c
  Hyunjin-Choi/boj/boj_11650.cpp
  Hyunjin-Choi/boj/boj_21866.cpp
  Hyunjin-Choi/boj/boj_2309.cpp
  Hyunjin-Choi/boj/boj_6603.cpp
  JongChan-Park/quiz1.js
  JongChan-Park/quiz2.java
  JongChan-Park/quiz3.java
  JongChan-Park/quiz4.java
  JongChan-Park/quiz5.java
  JongChan-Park/quiz6.java
  Minjung-Kim/N_Q1.c
  Minjung-Kim/README.txt
  Minjung-Kim/sort1_selectionSort.c
  Sunwoo-Han/boj/boj_13458.java
  Sunwoo-Han/boj/boj_14501.java
  Sunwoo-Han/boj/boj_16236.java
  Sunwoo-Han/programmers/bpMockexam.java
  Sunwoo-Han/programmers/sortBiggestNum.java
  Sunwoo-Han/programmers/sortHindex.java
Labels: C

#11 Weekly Pull Request - 최현진
  Hyunjin-Choi/boj/boj_1026.cpp
  Hyunjin-Choi/boj/boj_1037.cpp
  Hyunjin-Choi/boj/boj_1181.cpp
  Hyunjin-Choi/boj/boj_1920.cpp
  Hyunjin-Choi/boj/boj_2485.cpp
  Hyunjin-Choi/boj/boj_2693.cpp
  Hyunjin-Choi/boj/boj_2960.cpp
Labels: C, C++

#18 Weekly Pull Request - 이동윤 #15
  Dongyun-Lee/boj/boj_2490.java
  Dongyun-Lee/boj/boj_2884.java
  Dongyun-Lee/programmers/prog_1.java
  Dongyun-Lee/programmers/prog_2.java
  Dongyun-Lee/programmers/prog_3.java
Labels: Java

#19 Weekly Pull Request - 김민정
  Minjung-Kim/N_Q2_findIntersection.c
  Minjung-Kim/N_Q3_sort.c
  Minjung-Kim/N_Q4padding.c
  Minjung-Kim/N_Q5_POI.c
Labels: C

#20 Weekly Pull Request - 박종찬
  JongChan-Park/quiz15.java
  JongChan-Park/quiz17.java
  JongChan-Park/quiz18.java
  JongChan-Park/quiz19.java
  JongChan-Park/quiz20.java
  JongChan-Park/quiz21.java
Labels: Java

#24 Hyunjin choi
  Hyunjin-Choi/boj/boj_1075.cpp
  Hyunjin-Choi/boj/boj_10828.cpp
  Hyunjin-Choi/boj/boj_10867.cpp
  Hyunjin-Choi/boj/boj_1094.cpp
  Hyunjin-Choi/boj/boj_10989.cpp
  Hyunjin-Choi/boj/boj_1316.cpp
  Hyunjin-Choi/boj/boj_1684.cpp
  Hyunjin-Choi/boj/boj_17413.cpp
Labels: C++

#25 Weekly Pull Request - 이동윤
  Dongyun-Lee/boj/boj8958.java
  Dongyun-Lee/boj/boj_10818.java
  Dongyun-Lee/boj/boj_10871.java
  Dongyun-Lee/boj/boj_1110.java
  Dongyun-Lee/boj/boj_1546.java
  Dongyun-Lee/boj/boj_4344.java
  Dongyun-Lee/boj/boj_4673.java
Labels: Java

#26 Weekly Pull Request - 한선우
  Sunwoo-Han/boj/boj_10026.java
  Sunwoo-Han/boj/boj_11403.java
  Sunwoo-Han/boj/boj_11659.java
  Sunwoo-Han/boj/boj_11727.java
  Sunwoo-Han/boj/boj_17219.java
  Sunwoo-Han/boj/boj_17626.java
  Sunwoo-Han/boj/boj_9019.java
  Sunwoo-Han/boj/boj_9461.java
Labels: Java
